### ISSUE TITLE
[SUGGESTION] Forge port 1.18

### ISSUE THREAD

**Issue by TheRTGGaming** [28Pollux28/AchievementPlates#11]
This is the only mod that adds Achievement Plates. I was wondering if you can make a Forge Port to 1.18?

**Comment by 28Pollux28** [comment]
Already working on it, hopefully it will be available by Christmas

**Comment by 28Pollux28** [comment]
Done and released ! 
https://github.com/28Pollux28/AchievementPlates-FORGE
