### ISSUE TITLE
Blank Achievement Tile created upon respawn

### ISSUE THREAD

**Issue by nthnlws** [28Pollux28/AchievementPlates#2]
![2021-08-31_23 13 30](https://user-images.githubusercontent.com/88010944/131619305-2253708c-1756-470c-aa05-c7f1fb807732.png)
A blank achievement tile is created after every death (in inventory).

**Comment by 28Pollux28** [comment]
Sorry to bother you again, but what mods/ datapacks were you using ? I cannot reproduce this bug without mods
