### ISSUE TITLE
[SUGGESTION] Blacklist

### ISSUE THREAD

**Issue by gabriel-andreescu** [28Pollux28/AchievementPlates#5]
A blacklist would be useful, to block certain advancements

**Comment by DaFuqs** [comment]
A blacklist would be really cool. Especially when starting a new world players unlock lots of basic advancements to a time when inventory space is still pretty limited.
Being able to blacklist individual advancements or a whole namespace would be awesome. If I should help out with a PR I can do that no problem. 😁

**Comment by 28Pollux28** [comment]
I don't have much time rn but I'll do it. I've already played with blacklists so I know how to handle it.

**Comment by 28Pollux28** [comment]
This issue is now included in #7
